In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("indian_tech_jobs_2026.csv")

In [4]:
df.head()

,job_id,job_title,company_name,company_rating,location,scraped_city,role_category,experience_raw,experience_min_yrs,experience_max_yrs,...,scraped_at,salary_tier,experience_tier,is_senior,primary_city,skill_domain,salary_midpoint_lpa,days_since_posted,is_fresher_friendly,salary_negotiable
0,1,Data Scientist,Cisco,4.1,Bengaluru,Bangalore,Data Scientist,7-10 Yrs,7.0,10.0,...,2025-06-10,Undisclosed,Senior (6-8 Yrs),False,Bangalore,Business Intelligence,0.0,21.0,False,False
1,2,Data Scientist,Caterpillar Inc,4.1,Bengaluru,Bangalore,Data Scientist,4-8 Yrs,4.0,8.0,...,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Bangalore,AI/ML/DL,0.0,21.0,False,False
2,3,Analytics Data Scientist,Foreign IT Consulting MNC,3.6,"Hyderabad, Chennai, Bengaluru",Bangalore,Data Scientist,4-9 Yrs,4.0,9.0,...,2025-06-10,Undisclosed,Mid (3-5 Yrs),False,Hyderabad,Business Intelligence,0.0,21.0,False,False
3,4,Data Scientist,Fortune 500 IT Services Company,3.6,"Mumbai, Bengaluru",Bangalore,Data Scientist,10-14 Yrs,0.0,0.0,...,2025-06-10,Undisclosed,Fresher,False,Mumbai,Data Science,0.0,21.0,True,False
4,5,Sr. Artificial Intelligence Engineer,Fortune 500 Product-based MNC,3.6,"Pune, Bengaluru",Bangalore,Data Scientist,5-10 Yrs,5.0,10.0,...,2025-06-10,Undisclosed,Mid (3-5 Yrs),True,Pune,Data Science,0.0,21.0,False,False

In [10]:
df.describe()

,job_id,company_rating,experience_min_yrs,experience_max_yrs,salary_min_lpa,salary_max_lpa,skills_count,salary_midpoint_lpa,days_since_posted
count,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000,23201.000000
mean,11601.000000,3.586449,4.135080,7.829059,1.383952,2.271790,7.604198,1.827872,15.698935
std,6697.696134,0.514250,2.933976,3.946834,4.841570,7.469383,1.456530,6.109373,7.575881
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5801.000000,3.400000,2.000000,5.000000,0.000000,0.000000,8.000000,0.000000,7.000000
50%,11601.000000,3.600000,4.000000,8.000000,0.000000,0.000000,8.000000,0.000000,21.000000
75%,17401.000000,3.800000,6.000000,10.000000,0.000000,0.000000,8.000000,0.000000,21.000000
max,23201.000000,5.000000,25.000000,31.000000,85.000000,90.000000,8.000000,87.500000,90.000000

In [7]:
df["job_title"].value_counts()

job_title
Data Engineer                                                          847
Business Analyst                                                       829
Data Scientist                                                         516
Data Analyst                                                           404
Senior Data Engineer                                                   245
                                                                      ...
Business Operation and MIS Executive                                     1
Assistant Vice President - Business Intelligence and Insights Group      1
Manager - Business Planning & Analytics                                  1
Retail - Business Development Manager                                    1
Sales And Business Development Intern                                    1
Name: count, Length: 13128, dtype: int64

In [17]:
df.loc[1:23201,["job_title", "company_name"]].head(10)

,job_title,company_name
1,Data Scientist,Caterpillar Inc
2,Analytics Data Scientist,Foreign IT Consulting MNC
3,Data Scientist,Fortune 500 IT Services Company
4,Sr. Artificial Intelligence Engineer,Fortune 500 Product-based MNC
5,Data Scientist,Top Rated IT Enterprise
6,Data Scientist,Leading IT Firm
7,Advanced Data Scientist,Exxon Mobil Corporation
8,"Data Scientist, Google Play, Product",Google
9,Machine Learning Data Scientist,Hsbc
10,Sr Data Scientist - Advanced Machine Learning,Target

In [16]:
df["scraped_city"].value_counts().head(10).to_frame()

              count
scraped_city
Bangalore      3685
Mumbai         3368
Chennai        2693
Pune           2557
Delhi          2176
Noida          2147
Remote         1753
Kolkata        1701
Gurgaon        1636
Ahmedabad      1405